#!/usr/bin/env python3
"""
Renders the GitHub stat cards as SVG files committed straight into this repo.

Why: the public github-readme-stats.vercel.app instance is rate-limited and
its own README calls it "best-effort and unreliable". Every card it served was
rendering as a broken image. These SVGs are generated by GitHub Actions and
served from your own repo, so nothing third-party sits in the path.

Outputs:  assets/stats.svg  assets/languages.svg  assets/activity.svg

Run locally:  GITHUB_TOKEN=ghp_xxx python3 scripts/generate_cards.py
"""

import json
import os
import sys
import urllib.error
import urllib.request
from collections import Counter

USER = os.environ.get("GH_USERNAME", "getsurajmittal")
TOKEN = os.environ.get("GITHUB_TOKEN", "")
OUT = os.environ.get("ASSETS_DIR", "assets")

# Theme — keep in sync with the inline widget colours in README.md
BG      = "#0D1117"
BORDER  = "#1F2937"
TITLE   = "#00F5D4"
ACCENT  = "#8B5CF6"
TEXT    = "#C9D1D9"
MUTED   = "#8B949E"
FONT    = ("ui-monospace,'JetBrains Mono','SFMono-Regular',Consolas,"
           "'Liberation Mono',Menlo,monospace")

LANG_COLORS = {
    "JavaScript": "#F1E05A", "TypeScript": "#3178C6", "Python": "#3572A5",
    "Java": "#B07219", "C": "#555555", "C++": "#F34B7D", "C#": "#178600",
    "HTML": "#E34C26", "CSS": "#563D7C", "SCSS": "#C6538C", "Shell": "#89E051",
    "Go": "#00ADD8", "Rust": "#DEA584", "Ruby": "#701516", "PHP": "#4F5D95",
    "Dockerfile": "#384D54", "HCL": "#844FBA", "Makefile": "#427819",
    "PLpgSQL": "#336790", "Vue": "#41B883", "Kotlin": "#A97BFF",
    "Jupyter Notebook": "#DA5B0B", "Batchfile": "#C1F12E", "PowerShell": "#012456",
}


def log(m):
    print(m, flush=True)


def die(m):
    print(f"::error::{m}", file=sys.stderr, flush=True)
    sys.exit(1)


def esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


def rest(path, optional=False):
    req = urllib.request.Request(
        f"https://api.github.com{path}",
        headers={"Accept": "application/vnd.github+json",
                 "User-Agent": "profile-card-generator",
                 **({"Authorization": f"Bearer {TOKEN}"} if TOKEN else {})},
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.load(r)
    except Exception as e:
        if optional:
            log(f"  ! {type(e).__name__} on {path} — skipping")
            return None
        die(f"{type(e).__name__} on {path}: {e}")


def graphql(query, variables):
    if not TOKEN:
        return None
    req = urllib.request.Request(
        "https://api.github.com/graphql",
        data=json.dumps({"query": query, "variables": variables}).encode(),
        headers={"Authorization": f"Bearer {TOKEN}",
                 "Content-Type": "application/json",
                 "User-Agent": "profile-card-generator"},
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            body = json.load(r)
        if "errors" in body:
            log(f"  ! GraphQL: {body['errors'][0].get('message')}")
            return None
        return body.get("data")
    except Exception as e:
        log(f"  ! GraphQL unavailable ({type(e).__name__}) — falling back to REST")
        return None


# --------------------------------------------------------------------------- data

GQL = """
query($login:String!) {
  user(login:$login) {
    followers { totalCount }
    following { totalCount }
    repositories(first:1, ownerAffiliations:OWNER) { totalCount }
    pullRequests { totalCount }
    issues { totalCount }
    contributionsCollection {
      totalCommitContributions
      restrictedContributionsCount
      contributionCalendar {
        totalContributions
        weeks { contributionDays { contributionCount date } }
      }
    }
    repositoriesContributedTo(contributionTypes:[COMMIT,PULL_REQUEST,ISSUE,REPOSITORY]) {
      totalCount
    }
  }
}
"""


def gather():
    d = {"login": USER}

    user = rest(f"/users/{USER}")
    d["followers"] = user.get("followers", 0)
    d["following"] = user.get("following", 0)
    d["public_repos"] = user.get("public_repos", 0)
    d["name"] = user.get("name") or USER

    repos, page = [], 1
    while page <= 10:
        batch = rest(f"/users/{USER}/repos?per_page=100&page={page}&sort=pushed")
        if not batch:
            break
        repos.extend(batch)
        if len(batch) < 100:
            break
        page += 1
    owned = [r for r in repos if not r.get("fork")]
    d["stars"] = sum(r.get("stargazers_count", 0) for r in owned)
    d["forks"] = sum(r.get("forks_count", 0) for r in owned)

    # language byte totals across all non-fork repos
    langs = Counter()
    for r in owned:
        data = rest(f"/repos/{USER}/{r['name']}/languages", optional=True)
        if data:
            langs.update(data)
    d["languages"] = langs

    g = graphql(GQL, {"login": USER})
    if g and g.get("user"):
        u = g["user"]
        cc = u["contributionsCollection"]
        d["commits"] = cc["totalCommitContributions"] + cc.get("restrictedContributionsCount", 0)
        d["prs"] = u["pullRequests"]["totalCount"]
        d["issues"] = u["issues"]["totalCount"]
        d["contributed"] = u["repositoriesContributedTo"]["totalCount"]
        d["total_contributions"] = cc["contributionCalendar"]["totalContributions"]
        days = [(day["date"], day["contributionCount"])
                for w in cc["contributionCalendar"]["weeks"]
                for day in w["contributionDays"]]
        d["calendar"] = [c for _, c in days]
        d["calendar_days"] = days
    else:
        log("  (no token — commit/PR/issue counts unavailable, card adapts)")
        d.update(commits=None, prs=None, issues=None, contributed=None,
                 total_contributions=None, calendar=[], calendar_days=[])

    log(f"Gathered: {len(owned)} repos, {d['stars']} stars, "
        f"{len(langs)} languages, {len(d['calendar'])} contribution days")
    return d


# --------------------------------------------------------------------------- svg

def frame(w, h, title, body):
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" '
        f'viewBox="0 0 {w} {h}" role="img" aria-label="{esc(title)}">'
        f'<rect x="0.5" y="0.5" width="{w-1}" height="{h-1}" rx="10" '
        f'fill="{BG}" stroke="{BORDER}"/>'
        f'<text x="24" y="34" font-family="{FONT}" font-size="16" '
        f'font-weight="700" fill="{TITLE}">{esc(title)}</text>'
        f'{body}</svg>'
    )


def stats_card(d):
    w = 460
    if d["commits"] is not None:
        rows = [
            ("Total Stars Earned", d["stars"]),
            ("Total Commits", d["commits"]),
            ("Total PRs", d["prs"]),
            ("Total Issues", d["issues"]),
            ("Contributed to", d["contributed"]),
            ("Followers", d["followers"]),
        ]
    else:
        # No token: GraphQL-only metrics are unavailable, so show what REST gives.
        rows = [
            ("Total Stars Earned", d["stars"]),
            ("Total Forks", d["forks"]),
            ("Public Repos", d["public_repos"]),
            ("Followers", d["followers"]),
            ("Following", d["following"]),
        ]
    h = 70 + len(rows) * 26

    body = [f'<line x1="24" y1="46" x2="{w-24}" y2="46" stroke="{BORDER}"/>']
    y = 72
    for label, val in rows:
        body.append(
            f'<text x="24" y="{y}" font-family="{FONT}" font-size="13" '
            f'fill="{TEXT}">{esc(label)}</text>'
            f'<text x="{w-24}" y="{y}" font-family="{FONT}" font-size="13" '
            f'font-weight="700" text-anchor="end" fill="{ACCENT}">{val:,}</text>'
        )
        y += 26
    return frame(w, h, f"{d['name']} · GitHub Stats", "".join(body))


def languages_card(d):
    langs = d["languages"].most_common(8)
    if not langs:
        return frame(400, 90, "Most Used Languages",
                     f'<text x="24" y="66" font-family="{FONT}" font-size="13" '
                     f'fill="{MUTED}">No language data yet.</text>')

    total = sum(v for _, v in langs)
    w = 460
    bar_y, bar_h, bar_w = 60, 10, w - 48

    # stacked proportion bar
    body, x = [], 24.0
    for i, (name, val) in enumerate(langs):
        seg = bar_w * val / total
        r = 5 if i == 0 or i == len(langs) - 1 else 0
        body.append(
            f'<rect x="{x:.2f}" y="{bar_y}" width="{max(seg,1):.2f}" height="{bar_h}" '
            f'rx="{r}" fill="{LANG_COLORS.get(name, ACCENT)}"/>'
        )
        x += seg

    # two-column legend
    y0 = bar_y + 34
    col_w = (w - 48) / 2
    for i, (name, val) in enumerate(langs):
        cx = 24 + (i % 2) * col_w
        cy = y0 + (i // 2) * 24
        pct = 100 * val / total
        body.append(
            f'<circle cx="{cx+5}" cy="{cy-4}" r="5" fill="{LANG_COLORS.get(name, ACCENT)}"/>'
            f'<text x="{cx+18}" y="{cy}" font-family="{FONT}" font-size="12" '
            f'fill="{TEXT}">{esc(name)}</text>'
            f'<text x="{cx+col_w-14}" y="{cy}" font-family="{FONT}" font-size="12" '
            f'text-anchor="end" fill="{MUTED}">{pct:.1f}%</text>'
        )

    h = y0 + ((len(langs) + 1) // 2) * 24 + 8
    return frame(w, h, "Most Used Languages", "".join(body))


def activity_card(d):
    cal = d["calendar"]
    if not cal:
        return None

    weeks = [cal[i:i + 7] for i in range(0, len(cal), 7)][-53:]
    w, h = 940, 180
    cell, gap = 14, 3
    grid_w = len(weeks) * (cell + gap)
    x0 = max(24, (w - grid_w) // 2)
    y0 = 58

    peak = max(cal) or 1
    steps = [(0, "#161B22"), (0.25, "#0E4429"), (0.5, "#006D5B"),
             (0.75, "#00A88C"), (1.0, "#00F5D4")]

    def colour(n):
        if n == 0:
            return steps[0][1]
        frac = n / peak
        for limit, c in steps[1:]:
            if frac <= limit:
                return c
        return steps[-1][1]

    body = []
    for wi, week in enumerate(weeks):
        for di, n in enumerate(week):
            body.append(
                f'<rect x="{x0 + wi*(cell+gap)}" y="{y0 + di*(cell+gap)}" '
                f'width="{cell}" height="{cell}" rx="3" fill="{colour(n)}"/>'
            )

    legend_y = y0 + 7 * (cell + gap) + 22
    body.append(
        f'<text x="{x0}" y="{legend_y}" font-family="{FONT}" font-size="12" '
        f'fill="{MUTED}">{d["total_contributions"]:,} contributions in the last year</text>'
    )
    lx = x0 + grid_w - 150
    body.append(f'<text x="{lx-26}" y="{legend_y}" font-family="{FONT}" '
                f'font-size="11" fill="{MUTED}">Less</text>')
    for i, (_, c) in enumerate(steps):
        body.append(f'<rect x="{lx + i*17}" y="{legend_y-10}" width="12" height="12" '
                    f'rx="3" fill="{c}"/>')
    body.append(f'<text x="{lx + len(steps)*17 + 6}" y="{legend_y}" '
                f'font-family="{FONT}" font-size="11" fill="{MUTED}">More</text>')

    h = legend_y + 18
    return frame(w, h, "Contribution Activity", "".join(body))


# --------------------------------------------------------------------------- main

def write(name, svg):
    if svg is None:
        return
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, name)
    old = None
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            old = f.read()
    if old == svg:
        log(f"  = {path} unchanged")
        return
    with open(path, "w", encoding="utf-8") as f:
        f.write(svg)
    log(f"  + {path} written ({len(svg):,} bytes)")


TIERS = {
    "Commits":       [(5000, "SS"), (1000, "S"), (500, "A"), (100, "B"), (10, "C")],
    "Contributions": [(5000, "SS"), (1000, "S"), (500, "A"), (100, "B"), (10, "C")],
    "Active Days":   [(300, "SS"), (200, "S"), (100, "A"), (30, "B"), (5, "C")],
    "Best Streak":   [(365, "SS"), (100, "S"), (30, "A"), (7, "B"), (2, "C")],
    "Repos":         [(100, "SS"), (50, "S"), (20, "A"), (5, "B"), (1, "C")],
    "Languages":     [(15, "SS"), (10, "S"), (6, "A"), (3, "B"), (1, "C")],
    "Stars":         [(500, "SS"), (200, "S"), (50, "A"), (10, "B"), (1, "C")],
    "Followers":     [(500, "SS"), (100, "S"), (50, "A"), (10, "B"), (1, "C")],
    "Pull Reqs":     [(200, "SS"), (100, "S"), (50, "A"), (10, "B"), (1, "C")],
    "Issues":        [(100, "SS"), (50, "S"), (25, "A"), (10, "B"), (1, "C")],
}
TIER_COLOR = {"SS": "#FFD700", "S": "#00F5D4", "A": "#8B5CF6",
              "B": "#3B82F6", "C": "#10B981", "–": "#374151"}


def tier_of(metric, value):
    """Returns (tier letter, next threshold or None)."""
    ladder = TIERS[metric]
    for i, (need, letter) in enumerate(ladder):
        if value >= need:
            nxt = ladder[i - 1][0] if i > 0 else None
            return letter, nxt
    return "–", ladder[-1][0]


def trophies_card(d):
    """Replaces github-profile-trophy.vercel.app, which is rate-limited like the
    rest of that family. Shows where each metric actually stands plus progress
    to the next tier, rather than a wall of identical badges."""
    cal = d.get("calendar") or []
    active_days = sum(1 for n in cal if n > 0)
    best, run = 0, 0
    for n in cal:
        run = run + 1 if n > 0 else 0
        best = max(best, run)

    # Candidates in priority order. Only the non-zero ones are shown, so the card
    # reflects what you actually do rather than parading metrics you're at 0 on.
    candidates = [
        ("Commits", d["commits"] or 0),
        ("Contributions", d.get("total_contributions") or 0),
        ("Active Days", active_days),
        ("Best Streak", best),
        ("Repos", d["public_repos"]),
        ("Languages", len(d["languages"])),
        ("Stars", d["stars"]),
        ("Followers", d["followers"]),
        ("Pull Reqs", d["prs"] or 0),
        ("Issues", d["issues"] or 0),
    ]
    metrics = [c for c in candidates if c[1] > 0][:6]
    if len(metrics) < 6:  # pad so the grid stays full on a brand-new account
        metrics += [c for c in candidates if c[1] == 0][:6 - len(metrics)]

    w = 940
    cols, pad, gap = 3, 24, 16
    tile_w = (w - 2 * pad - (cols - 1) * gap) / cols
    tile_h = 96
    y0 = 58
    rows = (len(metrics) + cols - 1) // cols

    body = []
    for i, (name, val) in enumerate(metrics):
        cx = pad + (i % cols) * (tile_w + gap)
        cy = y0 + (i // cols) * (tile_h + gap)
        letter, nxt = tier_of(name, val)
        col = TIER_COLOR[letter]

        # progress toward the next tier
        if nxt:
            prev = next((n for n, l in TIERS[name] if l == letter), 0) if letter != "–" else 0
            span = max(nxt - prev, 1)
            frac = min(max((val - prev) / span, 0.0), 1.0)
            sub = f"{val:,} / {nxt:,} to {[l for n, l in TIERS[name] if n == nxt][0]}"
        else:
            frac, sub = 1.0, "max tier"

        bar_w = tile_w - 32
        body.append(
            f'<rect x="{cx:.1f}" y="{cy}" width="{tile_w:.1f}" height="{tile_h}" rx="8" '
            f'fill="#111823" stroke="{BORDER}"/>'
            f'<text x="{cx+16:.1f}" y="{cy+26}" font-family="{FONT}" font-size="12" '
            f'fill="{MUTED}">{esc(name)}</text>'
            f'<text x="{cx+16:.1f}" y="{cy+54}" font-family="{FONT}" font-size="24" '
            f'font-weight="700" fill="{TEXT}">{val:,}</text>'
            f'<rect x="{cx+tile_w-46:.1f}" y="{cy+14}" width="32" height="20" rx="6" '
            f'fill="{col}" opacity="0.18"/>'
            f'<text x="{cx+tile_w-30:.1f}" y="{cy+28}" font-family="{FONT}" font-size="12" '
            f'font-weight="700" text-anchor="middle" fill="{col}">{letter}</text>'
            f'<rect x="{cx+16:.1f}" y="{cy+68}" width="{bar_w:.1f}" height="5" rx="2.5" '
            f'fill="#1B2430"/>'
            f'<rect x="{cx+16:.1f}" y="{cy+68}" width="{max(bar_w*frac,2):.1f}" height="5" '
            f'rx="2.5" fill="{col}"/>'
            f'<text x="{cx+16:.1f}" y="{cy+88}" font-family="{FONT}" font-size="10" '
            f'fill="{MUTED}">{esc(sub)}</text>'
        )

    h = y0 + rows * (tile_h + gap) + 8
    return frame(w, h, "Milestones", "".join(body))


# --------------------------------------------------------------------- banners

SANS = ("system-ui,-apple-system,'Segoe UI',Roboto,'Helvetica Neue',"
        "Arial,sans-serif")

HEADER_NAME = os.environ.get("HEADER_NAME", "Suraj Mittal")
HEADER_TAGLINE = os.environ.get("HEADER_TAGLINE", "Agentic DevOps Software Engineer")


def wave_edge(w, y, amp, periods):
    """A smooth alternating wave across the full width, as a path fragment."""
    seg = w / (periods * 2)
    d, x, up = f"M0,{y:.1f}", 0.0, True
    for _ in range(periods * 2):
        d += (f" Q{x + seg/2:.1f},{y + (-amp if up else amp):.1f} "
              f"{x + seg:.1f},{y:.1f}")
        x += seg
        up = not up
    return d


def banner(w, h, stops, text=None, sub=None, wave_at="bottom", gid="g"):
    """Replaces capsule-render.vercel.app — same waving-gradient look, but the
    file lives in this repo so it can't 503 or rate-limit."""
    grad = "".join(
        f'<stop offset="{off}%" stop-color="{col}"/>' for off, col in stops
    )

    if wave_at == "bottom":
        base = h - 34
        path = wave_edge(w, base, 16, 2) + f" L{w},0 L0,0 Z"
    else:
        base = 34
        path = wave_edge(w, base, 16, 2) + f" L{w},{h} L0,{h} Z"

    body = [
        f'<defs><linearGradient id="{gid}" x1="0" y1="0" x2="1" y2="0">{grad}'
        f'</linearGradient></defs>',
        f'<path d="{path}" fill="url(#{gid})"/>',
    ]

    if text:
        cy = (base / 2) + 10
        body.append(
            f'<text x="{w/2:.0f}" y="{cy:.0f}" font-family="{SANS}" font-size="62" '
            f'font-weight="800" text-anchor="middle" fill="#FFFFFF" '
            f'letter-spacing="1">{esc(text)}</text>'
        )
        if sub:
            body.append(
                f'<text x="{w/2:.0f}" y="{cy + 40:.0f}" font-family="{SANS}" '
                f'font-size="19" font-weight="500" text-anchor="middle" '
                f'fill="#FFFFFF" opacity="0.82">{esc(sub)}</text>'
            )

    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" '
            f'viewBox="0 0 {w} {h}" role="img" '
            f'aria-label="{esc(text or "banner")}">' + "".join(body) + "</svg>")


def header_banner():
    return banner(1200, 230,
                  [(0, "#0F2027"), (50, "#203A43"), (100, "#00F5D4")],
                  text=HEADER_NAME, sub=HEADER_TAGLINE,
                  wave_at="bottom", gid="hdr")


def footer_banner():
    return banner(1200, 150,
                  [(0, "#00F5D4"), (50, "#203A43"), (100, "#0F2027")],
                  wave_at="top", gid="ftr")


def streak_card(d):
    """Replaces streak-stats.demolab.com. Same three-panel layout, computed from
    the contribution calendar we already fetch."""
    days = d.get("calendar_days") or []
    if not days:
        return None

    counts = [c for _, c in days]
    total = sum(counts)

    best = run = 0
    for c in counts:
        run = run + 1 if c > 0 else 0
        best = max(best, run)

    # Current streak: walk backwards. Today not yet committed doesn't break it.
    cur, started, ended = 0, None, None
    for date, c in reversed(days):
        if c > 0:
            cur += 1
            started = date
            ended = ended or date
        elif cur == 0:
            continue          # today still has time
        else:
            break

    months = "Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split()

    def pretty(iso, with_year=True):
        if not iso:
            return ""
        y, m, dd = iso.split("-")
        stamp = f"{months[int(m)-1]} {int(dd)}"
        return f"{stamp}, {y}" if with_year else stamp

    streak_span = (
        f"{pretty(started, False)} - {pretty(ended, False)}" if cur else "no active streak"
    )

    w, h = 460, 200
    col = w / 3
    body = [
        f'<line x1="{col:.0f}" y1="30" x2="{col:.0f}" y2="{h-30}" stroke="{BORDER}"/>',
        f'<line x1="{col*2:.0f}" y1="30" x2="{col*2:.0f}" y2="{h-30}" stroke="{BORDER}"/>',
    ]

    def panel(cx, value, label, sub, big_col):
        return (
            f'<text x="{cx:.0f}" y="88" font-family="{FONT}" font-size="30" '
            f'font-weight="700" text-anchor="middle" fill="{big_col}">{value}</text>'
            f'<text x="{cx:.0f}" y="116" font-family="{FONT}" font-size="12" '
            f'text-anchor="middle" fill="{TEXT}">{esc(label)}</text>'
            f'<text x="{cx:.0f}" y="138" font-family="{FONT}" font-size="10" '
            f'text-anchor="middle" fill="{MUTED}">{esc(sub)}</text>'
        )

    span = f"{pretty(days[0][0])} - Present"
    body.append(panel(col * 0.5, f"{total:,}", "Total Contributions", span, ACCENT))

    # centre panel: current streak inside a ring
    ccx, ccy = col * 1.5, 78
    body.append(
        f'<circle cx="{ccx:.0f}" cy="{ccy}" r="34" fill="none" '
        f'stroke="{TITLE}" stroke-width="3"/>'
        f'<text x="{ccx:.0f}" y="{ccy+10}" font-family="{FONT}" font-size="28" '
        f'font-weight="700" text-anchor="middle" fill="{ACCENT}">{cur}</text>'
        f'<text x="{ccx:.0f}" y="140" font-family="{FONT}" font-size="12" '
        f'font-weight="700" text-anchor="middle" fill="{TITLE}">Current Streak</text>'
        f'<text x="{ccx:.0f}" y="160" font-family="{FONT}" font-size="10" '
        f'text-anchor="middle" fill="{MUTED}">{esc(streak_span)}</text>'
    )

    body.append(panel(col * 2.5, f"{best}", "Longest Streak", "days in a row", ACCENT))

    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" '
            f'viewBox="0 0 {w} {h}" role="img" aria-label="Contribution streak">'
            f'<rect x="0.5" y="0.5" width="{w-1}" height="{h-1}" rx="10" '
            f'fill="{BG}" stroke="{BORDER}"/>' + "".join(body) + "</svg>")


def stamp_readme(names):
    """Append a content hash to each ./assets/<name>.svg reference in README.md.

    GitHub proxies README images through camo, which caches by URL. Regenerating
    an SVG at the same path leaves the stale image on screen — which is exactly
    what happened after the first run. Changing the query string changes the URL,
    so camo is forced to refetch.
    """
    import hashlib
    import re as _re

    path = os.environ.get("README_PATH", "README.md")
    if not os.path.exists(path):
        log(f"  ! {path} not found — skipping cache-bust stamp")
        return

    with open(path, encoding="utf-8") as f:
        content = original = f.read()

    for name in names:
        svg_path = os.path.join(OUT, f"{name}.svg")
        if not os.path.exists(svg_path):
            continue
        with open(svg_path, "rb") as f:
            digest = hashlib.md5(f.read()).hexdigest()[:8]
        content = _re.sub(
            rf'(\./{_re.escape(OUT)}/{_re.escape(name)}\.svg)(\?v=[0-9a-f]+)?',
            rf'\g<1>?v={digest}',
            content,
        )

    if content != original:
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        log("  + README image URLs re-stamped (cache-bust)")
    else:
        log("  = README image URLs already current")


def placeholder(title, w=460, h=140):
    """Neutral card used to seed assets/ before the first Actions run.

    Deliberately shows no numbers — a card with invented stats on a public
    profile is worse than one that says it hasn't run yet.
    """
    body = (
        f'<line x1="24" y1="46" x2="{w-24}" y2="46" stroke="{BORDER}"/>'
        f'<text x="24" y="78" font-family="{FONT}" font-size="13" fill="{TEXT}">'
        f'Populates on the first workflow run.</text>'
        f'<text x="24" y="102" font-family="{FONT}" font-size="12" fill="{MUTED}">'
        f'Actions &#8250; Auto-update README &#8250; Run workflow</text>'
    )
    return frame(w, h, title, body)


def main():
    names = ["header", "footer", "stats", "languages",
             "streak", "activity", "trophies"]

    # Banners hold no live data, so they're written the same way either mode.
    write("header.svg", header_banner())
    write("footer.svg", footer_banner())

    if "--placeholder" in sys.argv:
        write("stats.svg", placeholder("GitHub Stats"))
        write("languages.svg", placeholder("Most Used Languages"))
        write("streak.svg", placeholder("Contribution Streak"))
        write("activity.svg", placeholder("Contribution Activity", w=940))
        write("trophies.svg", placeholder("Milestones", w=940))
        stamp_readme(names)
        log("Placeholder cards written — run without --placeholder to fill them in.")
        return

    d = gather()
    write("stats.svg", stats_card(d))
    write("languages.svg", languages_card(d))
    write("streak.svg", streak_card(d) or placeholder("Contribution Streak"))
    write("activity.svg", activity_card(d))
    write("trophies.svg", trophies_card(d))
    stamp_readme(names)
    log("Cards done.")


if __name__ == "__main__":
    main()
