#!/usr/bin/env python3
"""
Renders the GitHub stat cards as SVG files committed straight into this repo.

Why: the public github-readme-stats.vercel.app instance is rate-limited and
its own README calls it "best-effort and unreliable". Every card it served was
rendering as a broken image. These SVGs are generated by GitHub Actions and
served from your own repo, so nothing third-party sits in the path.

Outputs:  assets/stats.svg  assets/languages.svg  assets/activity.svg

Run locally:  GITHUB_TOKEN=ghp_xxx python3 scripts/generate_cards.py
"""

import json
import os
import sys
import urllib.error
import urllib.request
from collections import Counter

USER = os.environ.get("GH_USERNAME", "getsurajmittal")
TOKEN = os.environ.get("GITHUB_TOKEN", "")
OUT = os.environ.get("ASSETS_DIR", "assets")

# Theme — keep in sync with the inline widget colours in README.md
BG      = "#0D1117"
BORDER  = "#1F2937"
TITLE   = "#00F5D4"
ACCENT  = "#8B5CF6"
TEXT    = "#C9D1D9"
MUTED   = "#8B949E"
FONT    = ("ui-monospace,'JetBrains Mono','SFMono-Regular',Consolas,"
           "'Liberation Mono',Menlo,monospace")

LANG_COLORS = {
    "JavaScript": "#F1E05A", "TypeScript": "#3178C6", "Python": "#3572A5",
    "Java": "#B07219", "C": "#555555", "C++": "#F34B7D", "C#": "#178600",
    "HTML": "#E34C26", "CSS": "#563D7C", "SCSS": "#C6538C", "Shell": "#89E051",
    "Go": "#00ADD8", "Rust": "#DEA584", "Ruby": "#701516", "PHP": "#4F5D95",
    "Dockerfile": "#384D54", "HCL": "#844FBA", "Makefile": "#427819",
    "PLpgSQL": "#336790", "Vue": "#41B883", "Kotlin": "#A97BFF",
    "Jupyter Notebook": "#DA5B0B", "Batchfile": "#C1F12E", "PowerShell": "#012456",
}


def log(m):
    print(m, flush=True)


def die(m):
    print(f"::error::{m}", file=sys.stderr, flush=True)
    sys.exit(1)


def esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


def rest(path, optional=False):
    req = urllib.request.Request(
        f"https://api.github.com{path}",
        headers={"Accept": "application/vnd.github+json",
                 "User-Agent": "profile-card-generator",
                 **({"Authorization": f"Bearer {TOKEN}"} if TOKEN else {})},
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.load(r)
    except Exception as e:
        if optional:
            log(f"  ! {type(e).__name__} on {path} — skipping")
            return None
        die(f"{type(e).__name__} on {path}: {e}")


def graphql(query, variables):
    if not TOKEN:
        return None
    req = urllib.request.Request(
        "https://api.github.com/graphql",
        data=json.dumps({"query": query, "variables": variables}).encode(),
        headers={"Authorization": f"Bearer {TOKEN}",
                 "Content-Type": "application/json",
                 "User-Agent": "profile-card-generator"},
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            body = json.load(r)
        if "errors" in body:
            log(f"  ! GraphQL: {body['errors'][0].get('message')}")
            return None
        return body.get("data")
    except Exception as e:
        log(f"  ! GraphQL unavailable ({type(e).__name__}) — falling back to REST")
        return None


# --------------------------------------------------------------------------- data

GQL = """
query($login:String!) {
  user(login:$login) {
    followers { totalCount }
    following { totalCount }
    repositories(first:1, ownerAffiliations:OWNER) { totalCount }
    pullRequests { totalCount }
    issues { totalCount }
    contributionsCollection {
      totalCommitContributions
      restrictedContributionsCount
      contributionCalendar {
        totalContributions
        weeks { contributionDays { contributionCount date } }
      }
    }
    repositoriesContributedTo(contributionTypes:[COMMIT,PULL_REQUEST,ISSUE,REPOSITORY]) {
      totalCount
    }
  }
}
"""


def gather():
    d = {"login": USER}

    user = rest(f"/users/{USER}")
    d["followers"] = user.get("followers", 0)
    d["following"] = user.get("following", 0)
    d["public_repos"] = user.get("public_repos", 0)
    d["name"] = user.get("name") or USER

    repos, page = [], 1
    while page <= 10:
        batch = rest(f"/users/{USER}/repos?per_page=100&page={page}&sort=pushed")
        if not batch:
            break
        repos.extend(batch)
        if len(batch) < 100:
            break
        page += 1
    owned = [r for r in repos if not r.get("fork")]
    d["stars"] = sum(r.get("stargazers_count", 0) for r in owned)
    d["forks"] = sum(r.get("forks_count", 0) for r in owned)

    # language byte totals across all non-fork repos
    langs = Counter()
    for r in owned:
        data = rest(f"/repos/{USER}/{r['name']}/languages", optional=True)
        if data:
            langs.update(data)
    d["languages"] = langs

    g = graphql(GQL, {"login": USER})
    if g and g.get("user"):
        u = g["user"]
        cc = u["contributionsCollection"]
        d["commits"] = cc["totalCommitContributions"] + cc.get("restrictedContributionsCount", 0)
        d["prs"] = u["pullRequests"]["totalCount"]
        d["issues"] = u["issues"]["totalCount"]
        d["contributed"] = u["repositoriesContributedTo"]["totalCount"]
        d["total_contributions"] = cc["contributionCalendar"]["totalContributions"]
        d["calendar"] = [
            day["contributionCount"]
            for w in cc["contributionCalendar"]["weeks"]
            for day in w["contributionDays"]
        ]
    else:
        log("  (no token — commit/PR/issue counts unavailable, card adapts)")
        d.update(commits=None, prs=None, issues=None,
                 contributed=None, total_contributions=None, calendar=[])

    log(f"Gathered: {len(owned)} repos, {d['stars']} stars, "
        f"{len(langs)} languages, {len(d['calendar'])} contribution days")
    return d


# --------------------------------------------------------------------------- svg

def frame(w, h, title, body):
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" '
        f'viewBox="0 0 {w} {h}" role="img" aria-label="{esc(title)}">'
        f'<rect x="0.5" y="0.5" width="{w-1}" height="{h-1}" rx="10" '
        f'fill="{BG}" stroke="{BORDER}"/>'
        f'<text x="24" y="34" font-family="{FONT}" font-size="16" '
        f'font-weight="700" fill="{TITLE}">{esc(title)}</text>'
        f'{body}</svg>'
    )


def stats_card(d):
    w = 460
    if d["commits"] is not None:
        rows = [
            ("Total Stars Earned", d["stars"]),
            ("Total Commits", d["commits"]),
            ("Total PRs", d["prs"]),
            ("Total Issues", d["issues"]),
            ("Contributed to", d["contributed"]),
            ("Followers", d["followers"]),
        ]
    else:
        # No token: GraphQL-only metrics are unavailable, so show what REST gives.
        rows = [
            ("Total Stars Earned", d["stars"]),
            ("Total Forks", d["forks"]),
            ("Public Repos", d["public_repos"]),
            ("Followers", d["followers"]),
            ("Following", d["following"]),
        ]
    h = 70 + len(rows) * 26

    body = [f'<line x1="24" y1="46" x2="{w-24}" y2="46" stroke="{BORDER}"/>']
    y = 72
    for label, val in rows:
        body.append(
            f'<text x="24" y="{y}" font-family="{FONT}" font-size="13" '
            f'fill="{TEXT}">{esc(label)}</text>'
            f'<text x="{w-24}" y="{y}" font-family="{FONT}" font-size="13" '
            f'font-weight="700" text-anchor="end" fill="{ACCENT}">{val:,}</text>'
        )
        y += 26
    return frame(w, h, f"{d['name']} · GitHub Stats", "".join(body))


def languages_card(d):
    langs = d["languages"].most_common(8)
    if not langs:
        return frame(400, 90, "Most Used Languages",
                     f'<text x="24" y="66" font-family="{FONT}" font-size="13" '
                     f'fill="{MUTED}">No language data yet.</text>')

    total = sum(v for _, v in langs)
    w = 460
    bar_y, bar_h, bar_w = 60, 10, w - 48

    # stacked proportion bar
    body, x = [], 24.0
    for i, (name, val) in enumerate(langs):
        seg = bar_w * val / total
        r = 5 if i == 0 or i == len(langs) - 1 else 0
        body.append(
            f'<rect x="{x:.2f}" y="{bar_y}" width="{max(seg,1):.2f}" height="{bar_h}" '
            f'rx="{r}" fill="{LANG_COLORS.get(name, ACCENT)}"/>'
        )
        x += seg

    # two-column legend
    y0 = bar_y + 34
    col_w = (w - 48) / 2
    for i, (name, val) in enumerate(langs):
        cx = 24 + (i % 2) * col_w
        cy = y0 + (i // 2) * 24
        pct = 100 * val / total
        body.append(
            f'<circle cx="{cx+5}" cy="{cy-4}" r="5" fill="{LANG_COLORS.get(name, ACCENT)}"/>'
            f'<text x="{cx+18}" y="{cy}" font-family="{FONT}" font-size="12" '
            f'fill="{TEXT}">{esc(name)}</text>'
            f'<text x="{cx+col_w-14}" y="{cy}" font-family="{FONT}" font-size="12" '
            f'text-anchor="end" fill="{MUTED}">{pct:.1f}%</text>'
        )

    h = y0 + ((len(langs) + 1) // 2) * 24 + 8
    return frame(w, h, "Most Used Languages", "".join(body))


def activity_card(d):
    cal = d["calendar"]
    if not cal:
        return None

    weeks = [cal[i:i + 7] for i in range(0, len(cal), 7)][-53:]
    w, h = 940, 180
    cell, gap = 14, 3
    grid_w = len(weeks) * (cell + gap)
    x0 = max(24, (w - grid_w) // 2)
    y0 = 58

    peak = max(cal) or 1
    steps = [(0, "#161B22"), (0.25, "#0E4429"), (0.5, "#006D5B"),
             (0.75, "#00A88C"), (1.0, "#00F5D4")]

    def colour(n):
        if n == 0:
            return steps[0][1]
        frac = n / peak
        for limit, c in steps[1:]:
            if frac <= limit:
                return c
        return steps[-1][1]

    body = []
    for wi, week in enumerate(weeks):
        for di, n in enumerate(week):
            body.append(
                f'<rect x="{x0 + wi*(cell+gap)}" y="{y0 + di*(cell+gap)}" '
                f'width="{cell}" height="{cell}" rx="3" fill="{colour(n)}"/>'
            )

    legend_y = y0 + 7 * (cell + gap) + 22
    body.append(
        f'<text x="{x0}" y="{legend_y}" font-family="{FONT}" font-size="12" '
        f'fill="{MUTED}">{d["total_contributions"]:,} contributions in the last year</text>'
    )
    lx = x0 + grid_w - 150
    body.append(f'<text x="{lx-26}" y="{legend_y}" font-family="{FONT}" '
                f'font-size="11" fill="{MUTED}">Less</text>')
    for i, (_, c) in enumerate(steps):
        body.append(f'<rect x="{lx + i*17}" y="{legend_y-10}" width="12" height="12" '
                    f'rx="3" fill="{c}"/>')
    body.append(f'<text x="{lx + len(steps)*17 + 6}" y="{legend_y}" '
                f'font-family="{FONT}" font-size="11" fill="{MUTED}">More</text>')

    h = legend_y + 18
    return frame(w, h, "Contribution Activity", "".join(body))


# --------------------------------------------------------------------------- main

def write(name, svg):
    if svg is None:
        return
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, name)
    old = None
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            old = f.read()
    if old == svg:
        log(f"  = {path} unchanged")
        return
    with open(path, "w", encoding="utf-8") as f:
        f.write(svg)
    log(f"  + {path} written ({len(svg):,} bytes)")


def placeholder(title, w=460, h=140):
    """Neutral card used to seed assets/ before the first Actions run.

    Deliberately shows no numbers — a card with invented stats on a public
    profile is worse than one that says it hasn't run yet.
    """
    body = (
        f'<line x1="24" y1="46" x2="{w-24}" y2="46" stroke="{BORDER}"/>'
        f'<text x="24" y="78" font-family="{FONT}" font-size="13" fill="{TEXT}">'
        f'Populates on the first workflow run.</text>'
        f'<text x="24" y="102" font-family="{FONT}" font-size="12" fill="{MUTED}">'
        f'Actions &#8250; Auto-update README &#8250; Run workflow</text>'
    )
    return frame(w, h, title, body)


def main():
    if "--placeholder" in sys.argv:
        write("stats.svg", placeholder("GitHub Stats"))
        write("languages.svg", placeholder("Most Used Languages"))
        write("activity.svg", placeholder("Contribution Activity", w=940))
        log("Placeholder cards written — run without --placeholder to fill them in.")
        return

    d = gather()
    write("stats.svg", stats_card(d))
    write("languages.svg", languages_card(d))
    write("activity.svg", activity_card(d))
    log("Cards done.")


if __name__ == "__main__":
    main()
